project:
  type: website
  output-dir: _site

execute: 
  echo: false
  freeze: auto

bibliography: _references.bib

website:
  title: "Canteras Microbiome"
  page-footer:
    left: |
      Canteras Microbiome Website was created by Vera Gómez-Limón Gallardo.
    center:
      - text: License
        href: LICENSE.md
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/averrasion/canteras-microbiome
  repo-actions: [source]
  bread-crumbs: true
  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "Our observations"
        href: intro.qmd
        contents: 
          - temperatures.qmd
          - nutrients.qmd
          - cells.qmd
          - enterococci.qmd
          - section: "Microbiome composition"
            href: asvs.qmd
            contents: 
              - asvs.qmd
              - taxonomy.qmd
              - ratios.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true