project:
  type: website
  output-dir: _site

execute: 
  echo: false
  freeze: auto

author:
  name: "Vera Gómez-Limón Gallardo"
  email: vera.gomez101@alu.ulpgc.es
date: last-modified
toc: true

bibliography: _references.bib

website:
  title: "Canteras Microbiome"
  page-footer:
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/averrasion/canteras-microbiome
  repo-actions: [source]
  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "Observations"
        href: temperatures.qmd
        contents: 
          - temperatures.qmd
          - nutrients.qmd
          - cells.qmd
          - enterococci.qmd
          - section: "Amplicon Sequence Variants"
            href: samples.qmd
            contents: 
              - samples.qmd
              - asv-overview.qmd
              - section: "Community Composition"
                href: prokaryotes.qmd
                contents: 
                - prokaryotes.qmd
                - eukaryotes.qmd
              - section: "Contamination Indicators"
                href: bacterial-indexes.qmd
                contents: 
                - bacterial-indexes.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true